logger:
  level: info
  file: ./bin/calendar.log
api:
  http:
    port: 8090
    connectionTimeout: 10
  grpc:
    port: 50051
    connectionTimeout: 10
storage:
  inMemoryStorage: true
  db:
    host: localhost
    port: 5432
    username: danny
    password: danny
    db: calendar
